In [33]:
import tensorflow
# from tensorflow.one_hot import one_hot

In [34]:
## sampel sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'i am a good boy',
    'i am  a good developer',
    'understand the meaning of words',
    'your videos are good',
]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am  a good developer',
 'understand the meaning of words',
 'your videos are good']

In [35]:
## define the vocabulary size
voc_size=10000

In [15]:
## one hot representation
from tensorflow.keras.preprocessing.text import one_hot
one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr

[[619, 9178, 6384, 7992],
 [619, 9178, 6384, 5945],
 [619, 9676, 6384, 7971],
 [6869, 4502, 2319, 4458, 9880],
 [6869, 4502, 2319, 4458, 7233],
 [3745, 619, 506, 6384, 3129],
 [2133, 5751, 5723, 4458]]

In [18]:
## word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
# from tf.keras.preprocessing import pad_sequence   ===> in older versions
# from tensorflow.keras.utils import pad_sequence
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [19]:
import numpy as np


In [20]:
sent_length=8
embedded_doc=pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
embedded_doc

array([[   0,    0,    0,    0,  619, 9178, 6384, 7992],
       [   0,    0,    0,    0,  619, 9178, 6384, 5945],
       [   0,    0,    0,    0,  619, 9676, 6384, 7971],
       [   0,    0,    0, 6869, 4502, 2319, 4458, 9880],
       [   0,    0,    0, 6869, 4502, 2319, 4458, 7233],
       [   0,    0,    0, 3745,  619,  506, 6384, 3129],
       [   0,    0,    0,    0, 2133, 5751, 5723, 4458]], dtype=int32)

In [21]:
## feature representation
dim=10


In [25]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_shape=(sent_length,)))
model.compile('adam', 'mse')
model.summary()


c:\Users\nandi\Desktop\DL-NLP\venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step


array([[[ 0.00753869, -0.02854905,  0.00413702, -0.02130836,
          0.04684589,  0.03194261,  0.03997784, -0.03577245,
          0.01407563, -0.04317934],
        [ 0.00753869, -0.02854905,  0.00413702, -0.02130836,
          0.04684589,  0.03194261,  0.03997784, -0.03577245,
          0.01407563, -0.04317934],
        [ 0.00753869, -0.02854905,  0.00413702, -0.02130836,
          0.04684589,  0.03194261,  0.03997784, -0.03577245,
          0.01407563, -0.04317934],
        [ 0.00753869, -0.02854905,  0.00413702, -0.02130836,
          0.04684589,  0.03194261,  0.03997784, -0.03577245,
          0.01407563, -0.04317934],
        [-0.04731395,  0.04443285,  0.00815759, -0.02527404,
         -0.02049925, -0.02761281,  0.02016648,  0.0086664 ,
         -0.02265973,  0.01849974],
        [-0.01660272,  0.03524463,  0.00309558, -0.02970433,
         -0.00890626, -0.04405922, -0.00975262, -0.01507624,
          0.0499741 , -0.0449402 ],
        [ 0.03978169,  0.03698858, -0.0440555 ,  0.0

In [28]:
embedded_doc[0]

array([   0,    0,    0,    0,  619, 9178, 6384, 7992], dtype=int32)

In [32]:
# model.predict(embedded_doc[0])
# model.predict([embedded_doc[0]])
import numpy as np
model.predict(np.expand_dims(embedded_doc[0], axis=0))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


array([[[ 0.00753869, -0.02854905,  0.00413702, -0.02130836,
          0.04684589,  0.03194261,  0.03997784, -0.03577245,
          0.01407563, -0.04317934],
        [ 0.00753869, -0.02854905,  0.00413702, -0.02130836,
          0.04684589,  0.03194261,  0.03997784, -0.03577245,
          0.01407563, -0.04317934],
        [ 0.00753869, -0.02854905,  0.00413702, -0.02130836,
          0.04684589,  0.03194261,  0.03997784, -0.03577245,
          0.01407563, -0.04317934],
        [ 0.00753869, -0.02854905,  0.00413702, -0.02130836,
          0.04684589,  0.03194261,  0.03997784, -0.03577245,
          0.01407563, -0.04317934],
        [-0.04731395,  0.04443285,  0.00815759, -0.02527404,
         -0.02049925, -0.02761281,  0.02016648,  0.0086664 ,
         -0.02265973,  0.01849974],
        [-0.01660272,  0.03524463,  0.00309558, -0.02970433,
         -0.00890626, -0.04405922, -0.00975262, -0.01507624,
          0.0499741 , -0.0449402 ],
        [ 0.03978169,  0.03698858, -0.0440555 ,  0.0